name: docker build
on: push

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-22.04
        timeout-minutes: 30
        strategy:
            fail-fast: false
            matrix:
                include:
                    - image: debian:stable

        container:
            image: ${{ matrix.image }}

        steps:
            - name: Checkout main repository
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
              with:
                  persist-credentials: false
            # - name: Checkout developer-meta-files
            #   uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
            #   with:
            #       repository: Kicksecure/developer-meta-files
            #       path: developer-meta-files
            - name: System Basic Packages
              run: |
                  apt-get update
                  apt-get install --yes --no-install-recommends wine fpc adduser shellcheck lazarus git ca-certificates libfile-mimeinfo-perl
            - name: Install Packages from Debian trixie
              run: |
                  echo 'Types: deb' | tee /etc/apt/sources.list.d/trixie.sources
                  echo 'URIs: https://deb.debian.org/debian' | tee -a /etc/apt/sources.list.d/trixie.sources
                  echo 'Suites: trixie' | tee -a /etc/apt/sources.list.d/trixie.sources
                  echo 'Components: main' | tee -a /etc/apt/sources.list.d/trixie.sources
                  echo 'Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg' | tee -a /etc/apt/sources.list.d/trixie.sources
                  apt-get update
                  apt-get install --yes --no-install-recommends fp-units-win-base fp-units-win-rtl fp-units-win-fcl fp-units-win-misc
            - name: System information
              run: |
                  whoami
                  cat /etc/os-release
                  uname -a
                  echo "${PATH}"
            - name: Create regular (non-root) user
              run: adduser --comment "" --disabled-password user
            - name: Linux user file permissions fix
              run: chown --recursive user:user /__w/Whonix-Installer
            - name: Build and run test.exe
              run: su -s /bin/bash user -- ./test.sh
            # - name: ppcross_install
            #   run: ./developer-meta-files/usr/bin/ppcross_install all
            - name: Build Installer
              run: su -s /bin/bash user -- ./build-dummy.sh
            - name: ShellCheck
              run: shellcheck ./*.sh
